/* ─────────────────────────────────────────────────────────────────────────────
 * Gigante Event Ops — Object Catalog
 * True-to-scale event-industry dimensions in FEET.
 * Reference standards: ASID, NFPA 101, AllSeated / Social Tables defaults,
 * standard hospitality-industry equipment specs.
 * ───────────────────────────────────────────────────────────────────────────── */

import type { ObjectKind } from "./types";

export const OBJECT_CATALOG: ObjectKind[] = [
  // ── SEATING — Round Tables ────────────────────────────────────────────────
  {
    kind: "round-36",
    category: "seating",
    label: '36" Round Table',
    shape: "circle",
    defaultWidthFt: 3.0,
    defaultHeightFt: 3.0,
    seats: 4,
    color: "muted",
    keepAspect: true,
    resizable: true,
    description: "Cocktail-style or kids' round; seats 4 with 18\" clearance per chair.",
  },
  {
    kind: "round-48",
    category: "seating",
    label: '48" Round Table',
    shape: "circle",
    defaultWidthFt: 4.0,
    defaultHeightFt: 4.0,
    seats: 6,
    color: "muted",
    keepAspect: true,
    resizable: true,
    description: "Standard round; seats 6. Common for rehearsal dinners, smaller events.",
  },
  {
    kind: "round-60",
    category: "seating",
    label: '60" Round Table',
    shape: "circle",
    defaultWidthFt: 5.0,
    defaultHeightFt: 5.0,
    seats: 8,
    color: "muted",
    keepAspect: true,
    resizable: true,
    description: "Most common banquet round; seats 8 comfortably, 10 tight.",
  },
  {
    kind: "round-72",
    category: "seating",
    label: '72" Round Table',
    shape: "circle",
    defaultWidthFt: 6.0,
    defaultHeightFt: 6.0,
    seats: 10,
    color: "muted",
    keepAspect: true,
    resizable: true,
    description: "Large round; seats 10. Requires ~5 ft aisles — use in large ballrooms.",
  },

  // ── SEATING — Banquet / Rectangle ─────────────────────────────────────────
  {
    kind: "banquet-6ft",
    category: "seating",
    label: "6 ft Banquet Table",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 2.5,
    seats: 6,
    color: "muted",
    resizable: true,
    description: "6 ft × 30\" folding banquet table; seats 3 per long side.",
  },
  {
    kind: "banquet-8ft",
    category: "seating",
    label: "8 ft Banquet Table",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 2.5,
    seats: 8,
    color: "muted",
    resizable: true,
    description: "8 ft × 30\" folding banquet table; seats 4 per long side.",
  },
  {
    kind: "serpentine",
    category: "seating",
    label: "Serpentine Table",
    shape: "rect",
    defaultWidthFt: 5.0,
    defaultHeightFt: 2.5,
    seats: 6,
    color: "muted",
    resizable: true,
    description: "S-curve / half-moon section; links with banquet tables for buffet lines.",
  },
  {
    kind: "square-48",
    category: "seating",
    label: '48" Square Table',
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 4.0,
    seats: 4,
    color: "muted",
    resizable: true,
    description: "Bistro-style square; seats 4 (one per side). Versatile for dinners.",
  },

  // ── SEATING — Cocktail / Hi-Top ───────────────────────────────────────────
  {
    kind: "cocktail-30",
    category: "seating",
    label: '30" Cocktail Table',
    shape: "circle",
    defaultWidthFt: 2.5,
    defaultHeightFt: 2.5,
    seats: 4,
    color: "gold",
    keepAspect: true,
    resizable: true,
    description: '30" round hi-top (42\" counter or bar height); 4 stools max.',
  },
  {
    kind: "cocktail-36",
    category: "seating",
    label: '36" Cocktail Table',
    shape: "circle",
    defaultWidthFt: 3.0,
    defaultHeightFt: 3.0,
    seats: 5,
    color: "gold",
    keepAspect: true,
    resizable: true,
    description: '36" round hi-top; 5 stools. Standard cocktail-hour table.',
  },

  // ── SEATING — Specialty Tables ────────────────────────────────────────────
  {
    kind: "sweetheart-table",
    category: "seating",
    label: "Sweetheart / King Table",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 2.5,
    seats: 2,
    color: "gold",
    resizable: true,
    description: "Small head table for couple/honorees; typically 4 ft × 30\".",
  },
  {
    kind: "farm-table",
    category: "seating",
    label: "Farm Table (8 ft)",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 3.0,
    seats: 10,
    color: "muted",
    resizable: true,
    description: "Rustic wood farm table 8 ft × 36\"; seats 5 per side.",
  },
  {
    kind: "head-table-12ft",
    category: "seating",
    label: "Head Table (12 ft)",
    shape: "rect",
    defaultWidthFt: 12.0,
    defaultHeightFt: 2.5,
    seats: 8,
    color: "gold",
    resizable: true,
    description: "Wedding/gala head table; seats only on one long side facing room.",
  },

  // ── SEATING — Chairs & Lounge ─────────────────────────────────────────────
  {
    kind: "chiavari-chair",
    category: "seating",
    label: "Chiavari Chair",
    shape: "rect",
    defaultWidthFt: 1.33,
    defaultHeightFt: 1.5,
    color: "muted",
    resizable: false,
    description: "Standard chiavari/ballroom chair 16\" wide × 18\" deep.",
  },
  {
    kind: "lounge-sofa",
    category: "seating",
    label: "Lounge Sofa",
    shape: "rect",
    defaultWidthFt: 7.0,
    defaultHeightFt: 3.0,
    seats: 3,
    color: "vip",
    resizable: true,
    description: "Event lounge sofa (typical rental: 7 ft × 36\"). Seats 3.",
  },
  {
    kind: "lounge-chair",
    category: "seating",
    label: "Lounge Chair",
    shape: "rect",
    defaultWidthFt: 3.0,
    defaultHeightFt: 3.0,
    seats: 1,
    color: "vip",
    resizable: true,
    description: "Club/lounge chair approx 36\" × 36\". Pairs with sofa sets.",
  },
  {
    kind: "coffee-table",
    category: "seating",
    label: "Coffee Table",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 2.0,
    color: "muted",
    resizable: true,
    description: "Lounge coffee table approx 48\" × 24\".",
  },
  {
    kind: "side-table",
    category: "seating",
    label: "Side / End Table",
    shape: "circle",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.5,
    color: "muted",
    keepAspect: true,
    resizable: true,
    description: "Small round side table 18\" diameter for lounge areas.",
  },
  {
    kind: "lounge-rug",
    category: "decor",
    label: "Lounge Rug / Area Rug",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 10.0,
    color: "vip",
    resizable: true,
    description: "8×10 event lounge rug defining a seating vignette.",
  },

  // ── BAR ───────────────────────────────────────────────────────────────────
  {
    kind: "bar-straight-6ft",
    category: "bar",
    label: "Bar Section (6 ft)",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 2.0,
    color: "gold",
    resizable: true,
    description: "Single straight bar section 6 ft × 24\". Stackable to build longer bars.",
  },
  {
    kind: "bar-straight-8ft",
    category: "bar",
    label: "Bar Section (8 ft)",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 2.0,
    color: "gold",
    resizable: true,
    description: "8 ft straight bar section × 24\" deep.",
  },
  {
    kind: "bar-portable",
    category: "bar",
    label: "Portable / Mobile Bar",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 2.5,
    color: "gold",
    resizable: true,
    description: "Self-contained portable bar with under-counter storage; 6 ft × 30\".",
  },
  {
    kind: "bar-u-shape-10ft",
    category: "bar",
    label: "U-Shape Bar Station (10 ft)",
    shape: "rect",
    defaultWidthFt: 10.0,
    defaultHeightFt: 5.0,
    color: "gold",
    resizable: true,
    description: "U-shape configuration 10 ft wide × 5 ft deep (White Party poolside standard).",
  },
  {
    kind: "back-bar",
    category: "bar",
    label: "Back Bar",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 1.5,
    color: "gold",
    resizable: true,
    description: "Back-bar display / speed rail 6 ft × 18\". Placed behind front bar.",
  },
  {
    kind: "service-station",
    category: "bar",
    label: "Service / Bus Station",
    shape: "rect",
    defaultWidthFt: 3.0,
    defaultHeightFt: 2.0,
    color: "muted",
    resizable: true,
    description: "Server pick-up / bus station 3 ft × 24\". Linen, glassware, supplies.",
  },
  {
    kind: "draft-keg-station",
    category: "bar",
    label: "Draft / Keg Station",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 2.0,
    color: "muted",
    resizable: true,
    description: "Draft beer tower + jockey box / keg well; 4 ft × 24\".",
  },
  {
    kind: "pos-stand",
    category: "bar",
    label: "POS / Handheld Stand",
    shape: "rect",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.5,
    color: "ok",
    resizable: false,
    description: "Toast POS terminal or handheld cradle/stand; footprint ~18\" × 18\".",
  },
  {
    kind: "transfer-station",
    category: "bar",
    label: "Transfer / Glass-Swap Station",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 2.5,
    color: "vip",
    resizable: true,
    description: "Pool-entry glass-to-plastic transfer station; 4 ft × 30\". White Party standard.",
  },

  // ── STAGE / AV ────────────────────────────────────────────────────────────
  {
    kind: "stage-riser-4x8",
    category: "stage",
    label: "Stage Riser (4×8 ft)",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 4.0,
    color: "muted",
    resizable: false,
    description: "Standard 4×8 ft stage deck/riser (Staging Concepts, Staging Simple, etc.).",
  },
  {
    kind: "stage-riser-8x8",
    category: "stage",
    label: "Stage Riser (8×8 ft)",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 8.0,
    color: "muted",
    resizable: false,
    description: "8×8 ft stage riser module. Combine multiple units to build stage.",
  },
  {
    kind: "dj-booth",
    category: "stage",
    label: "DJ Booth",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 4.0,
    color: "gold",
    resizable: true,
    description: "DJ table + flight cases; typical footprint 6 ft wide × 4 ft deep.",
  },
  {
    kind: "dance-floor-panel",
    category: "stage",
    label: "Dance Floor Panel (3×3)",
    shape: "rect",
    defaultWidthFt: 3.0,
    defaultHeightFt: 3.0,
    color: "muted",
    resizable: false,
    description: "Single portable dance floor panel 3×3 ft. Tile together for total floor size.",
  },
  {
    kind: "dance-floor-area",
    category: "stage",
    label: "Dance Floor Area",
    shape: "rect",
    defaultWidthFt: 18.0,
    defaultHeightFt: 18.0,
    color: "#a78bfa",
    resizable: true,
    description: "Dance floor boundary block. Default 18×18 ft (~300 guests light dancing).",
  },
  {
    kind: "speaker-main",
    category: "stage",
    label: "Speaker (Main / PA)",
    shape: "rect",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.5,
    color: "muted",
    resizable: false,
    description: "Main PA speaker on stand or ground stack; footprint ~18\" × 18\".",
  },
  {
    kind: "speaker-sub",
    category: "stage",
    label: "Subwoofer",
    shape: "rect",
    defaultWidthFt: 2.0,
    defaultHeightFt: 2.0,
    color: "muted",
    resizable: false,
    description: "18\" subwoofer cabinet ground-stacked; footprint ~24\" × 24\".",
  },
  {
    kind: "lighting-truss",
    category: "stage",
    label: "Lighting Truss / Tower",
    shape: "rect",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.5,
    color: "muted",
    resizable: true,
    description: "Ground-support lighting truss base or totem tower; 18\" × 18\" footprint.",
  },
  {
    kind: "foh-av-table",
    category: "stage",
    label: "FOH / AV Table",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 3.0,
    color: "muted",
    resizable: true,
    description: "Front-of-house mix position; 8 ft × 36\" console + gear table.",
  },
  {
    kind: "photo-booth",
    category: "stage",
    label: "Photo Booth",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 6.0,
    color: "gold",
    resizable: true,
    description: "Open-air or enclosed photo booth; 8 ft wide × 6 ft deep including backdrop.",
  },
  {
    kind: "screen-projector",
    category: "stage",
    label: "Screen / Projection Screen",
    shape: "rect",
    defaultWidthFt: 9.0,
    defaultHeightFt: 5.0,
    color: "muted",
    resizable: true,
    description: "9×5 ft fast-fold 16:9 projection screen (pipe-mounted or on legs).",
  },
  {
    kind: "monitor-wedge",
    category: "stage",
    label: "Stage Monitor / Wedge",
    shape: "rect",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.0,
    color: "muted",
    resizable: false,
    description: "Floor monitor wedge; 15\"×12\" footprint.",
  },

  // ── STRUCTURE ─────────────────────────────────────────────────────────────
  {
    kind: "doorway-single",
    category: "structure",
    label: "Single Doorway",
    shape: "rect",
    defaultWidthFt: 3.5,
    defaultHeightFt: 0.5,
    color: "#60a5fa",
    resizable: true,
    description: "Standard 36\" single door opening shown as a gap in the wall.",
  },
  {
    kind: "doorway-double",
    category: "structure",
    label: "Double Doorway",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 0.5,
    color: "#60a5fa",
    resizable: true,
    description: "6 ft double-door entry opening.",
  },
  {
    kind: "entrance-gate",
    category: "structure",
    label: "Entrance Gate / Arch",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 2.0,
    color: "gold",
    resizable: true,
    description: "Decorative entrance gate or event arch; 8 ft wide × 2 ft deep footprint.",
  },
  {
    kind: "stanchion-post",
    category: "structure",
    label: "Stanchion Post",
    shape: "circle",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "muted",
    keepAspect: true,
    resizable: false,
    description: "Single rope/belt stanchion post; ~12\" base diameter.",
  },
  {
    kind: "pipe-drape-10ft",
    category: "structure",
    label: "Pipe & Drape Section (10 ft)",
    shape: "rect",
    defaultWidthFt: 10.0,
    defaultHeightFt: 1.0,
    color: "muted",
    resizable: true,
    description: "10 ft pipe-and-drape panel; 1 ft depth for upright bases.",
  },
  {
    kind: "wall-partition",
    category: "structure",
    label: "Wall / Partition",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 0.5,
    color: "#94a3b8",
    resizable: true,
    description: "Temporary wall panel or existing wall segment; 8 ft × 6\" depth.",
  },
  {
    kind: "tent-20x20",
    category: "structure",
    label: "Tent (20×20 ft)",
    shape: "rect",
    defaultWidthFt: 20.0,
    defaultHeightFt: 20.0,
    color: "muted",
    resizable: true,
    description: "20×20 ft frame tent; ~30 guests seated, ~60 cocktail.",
  },
  {
    kind: "tent-20x40",
    category: "structure",
    label: "Tent (20×40 ft)",
    shape: "rect",
    defaultWidthFt: 40.0,
    defaultHeightFt: 20.0,
    color: "muted",
    resizable: true,
    description: "20×40 ft frame tent; ~60 guests seated, ~120 cocktail.",
  },
  {
    kind: "pole-column",
    category: "structure",
    label: "Column / Pole",
    shape: "circle",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "#94a3b8",
    keepAspect: true,
    resizable: false,
    description: "Structural column or tent pole; ~12\" diameter footprint.",
  },
  {
    kind: "coat-check",
    category: "structure",
    label: "Coat Check",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 3.0,
    color: "muted",
    resizable: true,
    description: "Coat check area; 6 ft × 3 ft including garment rack footprint.",
  },
  {
    kind: "box-office-table",
    category: "structure",
    label: "Box Office / Ticket Table",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 2.5,
    color: "ok",
    resizable: true,
    description: "Entry box office / check-in table; 6 ft × 30\".",
  },
  {
    kind: "ramp",
    category: "structure",
    label: "Ramp",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 6.0,
    color: "muted",
    resizable: true,
    description: "ADA ramp or stage access ramp; 4 ft wide × 6 ft run (1:12 slope).",
  },
  {
    kind: "stairs",
    category: "structure",
    label: "Stairs",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 3.0,
    color: "muted",
    resizable: true,
    description: "Staircase landing footprint; 4 ft wide × 3 ft run.",
  },

  // ── DECOR ─────────────────────────────────────────────────────────────────
  {
    kind: "balloon-arch",
    category: "decor",
    label: "Balloon Arch / Garland",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 3.0,
    color: "gold",
    resizable: true,
    description: "Balloon arch or organic garland; 8 ft span × ~3 ft depth.",
  },
  {
    kind: "floral-centerpiece",
    category: "decor",
    label: "Floral Arrangement / Centerpiece",
    shape: "circle",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "gold",
    keepAspect: true,
    resizable: true,
    description: "Table centerpiece; ~12\" diameter base footprint.",
  },
  {
    kind: "plinth-pedestal",
    category: "decor",
    label: "Plinth / Pedestal",
    shape: "circle",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "muted",
    keepAspect: true,
    resizable: true,
    description: "Decorative plinth or pedestal column; ~12\" diameter.",
  },
  {
    kind: "backdrop-step-repeat",
    category: "decor",
    label: "Backdrop / Step & Repeat",
    shape: "rect",
    defaultWidthFt: 8.0,
    defaultHeightFt: 1.0,
    color: "muted",
    resizable: true,
    description: "8 ft wide step-and-repeat or fabric backdrop; 1 ft depth.",
  },
  {
    kind: "gobo-projection",
    category: "decor",
    label: "GOBO / Projection",
    shape: "circle",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "#a78bfa",
    keepAspect: true,
    resizable: false,
    description: "GOBO or pattern projector footprint (the fixture, not the projected area).",
  },
  {
    kind: "uplight",
    category: "decor",
    label: "Uplight / LED Par",
    shape: "circle",
    defaultWidthFt: 0.75,
    defaultHeightFt: 0.75,
    color: "#f59e0b",
    keepAspect: true,
    resizable: false,
    description: "LED PAR or uplight can; 9\" base diameter.",
  },
  {
    kind: "neon-sign",
    category: "decor",
    label: "Neon Sign",
    shape: "rect",
    defaultWidthFt: 3.0,
    defaultHeightFt: 1.5,
    color: "#f43f5e",
    resizable: true,
    description: "Custom LED neon sign; typical 36\" × 18\" frame.",
  },
  {
    kind: "candelabra",
    category: "decor",
    label: "Candelabra / Tall Floral",
    shape: "circle",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.5,
    color: "gold",
    keepAspect: true,
    resizable: true,
    description: "Tall candelabra or elevated floral; 18\" base footprint.",
  },
  {
    kind: "planter-greenery",
    category: "decor",
    label: "Planter / Greenery",
    shape: "circle",
    defaultWidthFt: 2.0,
    defaultHeightFt: 2.0,
    color: "#22c55e",
    keepAspect: true,
    resizable: true,
    description: "Large decorative planter or faux-hedge greenery panel; ~24\" diameter.",
  },
  {
    kind: "marquee-letters",
    category: "decor",
    label: "Marquee Letters",
    shape: "rect",
    defaultWidthFt: 10.0,
    defaultHeightFt: 3.5,
    color: "gold",
    resizable: true,
    description: 'Marquee light-up letter set (e.g. "LOVE"); ~3.5 ft tall per letter.',
  },

  // ── EFFECTS (category: decor) ─────────────────────────────────────────────
  {
    kind: "co2-jet",
    category: "decor",
    label: "CO₂ Jet",
    shape: "rect",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "#38bdf8",
    resizable: false,
    description: "CO₂ cryo jet; 12\" × 12\" base. Mark direction of blast.",
  },
  {
    kind: "cold-spark",
    category: "decor",
    label: "Cold Spark Fountain",
    shape: "circle",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "#fbbf24",
    keepAspect: true,
    resizable: false,
    description: "Cold-spark / gerb fountain; ~12\" base. 15 ft clearance radius needed.",
  },
  {
    kind: "fog-haze-machine",
    category: "decor",
    label: "Fog / Haze Machine",
    shape: "rect",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.0,
    color: "muted",
    resizable: false,
    description: "Fog or haze machine; 18\" × 12\" unit footprint.",
  },
  {
    kind: "confetti-cannon",
    category: "decor",
    label: "Confetti Cannon",
    shape: "rect",
    defaultWidthFt: 1.0,
    defaultHeightFt: 1.0,
    color: "gold",
    resizable: false,
    description: "Handheld or rig-mounted confetti cannon; ~12\" footprint.",
  },
  {
    kind: "bubble-machine",
    category: "decor",
    label: "Bubble Machine",
    shape: "rect",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.0,
    color: "#7dd3fc",
    resizable: false,
    description: "Electric bubble machine; 18\" × 12\" footprint.",
  },

  // ── POOL ─────────────────────────────────────────────────────────────────
  {
    kind: "pool-lounge-chair",
    category: "pool",
    label: "Pool Lounge Chair / Chaise",
    shape: "rect",
    defaultWidthFt: 2.0,
    defaultHeightFt: 6.0,
    color: "pool",
    resizable: true,
    description: "Standard pool chaise longue; 24\" × 72\".",
  },
  {
    kind: "pool-daybed",
    category: "pool",
    label: "Pool Daybed",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 7.0,
    seats: 2,
    color: "pool",
    resizable: true,
    description: "Daybed / double chaise; 48\" × 84\". Often elevated with side tables.",
  },
  {
    kind: "cabana",
    category: "pool",
    label: "Cabana",
    shape: "rect",
    defaultWidthFt: 10.0,
    defaultHeightFt: 10.0,
    color: "vip",
    resizable: true,
    description: "Private poolside cabana enclosure; typical 10×10 ft.",
  },
  {
    kind: "patio-umbrella",
    category: "pool",
    label: "Patio Umbrella",
    shape: "circle",
    defaultWidthFt: 9.0,
    defaultHeightFt: 9.0,
    color: "#0ea5e9",
    keepAspect: true,
    resizable: true,
    description: "Market umbrella 9 ft diameter canopy.",
  },
  {
    kind: "pool-side-table",
    category: "pool",
    label: "Pool Side Table",
    shape: "circle",
    defaultWidthFt: 1.5,
    defaultHeightFt: 1.5,
    color: "pool",
    keepAspect: true,
    resizable: true,
    description: "Small round side table at pool; 18\" diameter.",
  },
  {
    kind: "pool-float",
    category: "pool",
    label: "Float / Inflatable",
    shape: "circle",
    defaultWidthFt: 4.0,
    defaultHeightFt: 4.0,
    color: "#f9a8d4",
    keepAspect: true,
    resizable: true,
    description: "Pool float or decorative inflatable; approx 48\" diameter.",
  },
  {
    kind: "pool-edge-marker",
    category: "pool",
    label: "Pool-Edge Marker",
    shape: "rect",
    defaultWidthFt: 1.0,
    defaultHeightFt: 0.5,
    color: "warn",
    resizable: false,
    description: "Safety cone / edge marker at pool perimeter.",
  },
  {
    kind: "lifeguard-stand",
    category: "pool",
    label: "Lifeguard Stand",
    shape: "rect",
    defaultWidthFt: 3.0,
    defaultHeightFt: 3.0,
    color: "#ef4444",
    resizable: false,
    description: "Lifeguard observation tower; ~3 ft × 3 ft base.",
  },
  {
    kind: "towel-station",
    category: "pool",
    label: "Towel Station",
    shape: "rect",
    defaultWidthFt: 3.0,
    defaultHeightFt: 2.0,
    color: "pool",
    resizable: true,
    description: "Towel distribution cart/stand; 3 ft × 24\" footprint.",
  },

  // ── BOH ───────────────────────────────────────────────────────────────────
  {
    kind: "prep-table",
    category: "boh",
    label: "Prep Table",
    shape: "rect",
    defaultWidthFt: 6.0,
    defaultHeightFt: 2.5,
    color: "muted",
    resizable: true,
    description: "Stainless prep table 6 ft × 30\". NSF food-safe surface.",
  },
  {
    kind: "ice-bin",
    category: "boh",
    label: "Ice Bin / Chest",
    shape: "rect",
    defaultWidthFt: 2.5,
    defaultHeightFt: 1.5,
    color: "#7dd3fc",
    resizable: true,
    description: "200–300 lb ice chest; 30\" × 18\" footprint.",
  },
  {
    kind: "trash-recycling",
    category: "boh",
    label: "Trash / Recycling",
    shape: "circle",
    defaultWidthFt: 2.0,
    defaultHeightFt: 2.0,
    color: "muted",
    keepAspect: true,
    resizable: false,
    description: "32-gal trash or recycling bin; 24\" diameter.",
  },
  {
    kind: "handwash-sink",
    category: "boh",
    label: "Handwash Sink",
    shape: "rect",
    defaultWidthFt: 2.0,
    defaultHeightFt: 2.0,
    color: "#7dd3fc",
    resizable: false,
    description: "NSF portable handwash sink unit; 24\" × 24\".",
  },
  {
    kind: "hot-box-cambro",
    category: "boh",
    label: "Hot Box / Cambro",
    shape: "rect",
    defaultWidthFt: 2.0,
    defaultHeightFt: 2.0,
    color: "warn",
    resizable: false,
    description: "Insulated cambro or hot-holding box; approx 24\" × 24\".",
  },
  {
    kind: "bus-tub-rack",
    category: "boh",
    label: "Dish / Bus Tub Rack",
    shape: "rect",
    defaultWidthFt: 2.0,
    defaultHeightFt: 2.0,
    color: "muted",
    resizable: false,
    description: "Glassware bus rack or sheet-pan rack; 20\" × 20\" footprint.",
  },
  {
    kind: "dry-storage-rack",
    category: "boh",
    label: "Dry Storage Rack",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 1.5,
    color: "muted",
    resizable: true,
    description: "Wire shelving unit 4 ft × 18\" for dry goods, supplies.",
  },
  {
    kind: "generator",
    category: "boh",
    label: "Generator",
    shape: "rect",
    defaultWidthFt: 4.0,
    defaultHeightFt: 3.0,
    color: "warn",
    resizable: true,
    description: "Portable generator; typical 8–12 kW unit ~48\" × 36\". Needs ventilation clearance.",
  },
  {
    kind: "power-distro",
    category: "boh",
    label: "Power Distribution Box",
    shape: "rect",
    defaultWidthFt: 2.0,
    defaultHeightFt: 1.5,
    color: "warn",
    resizable: false,
    description: "120/208V power distro unit; 24\" × 18\" panel box.",
  },
  {
    kind: "cooler-reach-in",
    category: "boh",
    label: "Cooler / Reach-In",
    shape: "rect",
    defaultWidthFt: 3.0,
    defaultHeightFt: 2.5,
    color: "#7dd3fc",
    resizable: true,
    description: "Portable reach-in cooler or True merchandiser; 36\" × 30\".",
  },
  {
    kind: "fire-extinguisher",
    category: "boh",
    label: "Fire Extinguisher",
    shape: "circle",
    defaultWidthFt: 0.5,
    defaultHeightFt: 0.5,
    color: "#ef4444",
    keepAspect: true,
    resizable: false,
    description: "5 lb ABC extinguisher on stand; 6\" footprint. Mark all locations.",
  },
  {
    kind: "first-aid-station",
    category: "boh",
    label: "First Aid Station",
    shape: "rect",
    defaultWidthFt: 2.0,
    defaultHeightFt: 1.5,
    color: "#ef4444",
    resizable: false,
    description: "First-aid kit cabinet or AED station; 24\" × 18\".",
  },

  // ── MARKUP ────────────────────────────────────────────────────────────────
  {
    kind: "markup-text",
    category: "markup",
    label: "Text Label",
    shape: "text",
    defaultWidthFt: 6.0,
    defaultHeightFt: 1.0,
    color: "muted",
    resizable: true,
    description: "Free-form text annotation. Double-click to edit.",
  },
  {
    kind: "markup-arrow",
    category: "markup",
    label: "Arrow",
    shape: "line",
    defaultWidthFt: 6.0,
    defaultHeightFt: 0.5,
    color: "muted",
    resizable: true,
    description: "Directional arrow for flow / egress / delivery routes.",
  },
  {
    kind: "markup-dimension",
    category: "markup",
    label: "Dimension Line",
    shape: "line",
    defaultWidthFt: 10.0,
    defaultHeightFt: 0.5,
    color: "#64748b",
    resizable: true,
    description: "Dimension callout line with end-caps. Use to annotate real distances.",
  },
  {
    kind: "markup-zone",
    category: "markup",
    label: "Zone Polygon",
    shape: "polygon",
    defaultWidthFt: 20.0,
    defaultHeightFt: 20.0,
    color: "vip",
    resizable: true,
    description: "Freeform zone boundary polygon. Assign a color and label.",
  },
  {
    kind: "markup-area-block",
    category: "markup",
    label: "Area Block",
    shape: "rect",
    defaultWidthFt: 10.0,
    defaultHeightFt: 10.0,
    color: "muted",
    resizable: true,
    description: "Rectangular zone/area highlight. Use for stages, dance floors, FOH, etc.",
  },
  {
    kind: "markup-scale-note",
    category: "markup",
    label: "Scale / Measurement Note",
    shape: "text",
    defaultWidthFt: 4.0,
    defaultHeightFt: 0.75,
    color: "#64748b",
    resizable: true,
    description: "Scale reference note, e.g. '1 unit = 1 ft'. Place near floor plan edge.",
  },
];
